version: '3.8.1'

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - data-volume:/var/lib/postgresql
  app:
    build: .
    container_name: app_con
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      - db

volumes:
  data-volume:
  